### ISSUE TITLE
Add CLI

### ISSUE THREAD

**Issue by anoff** [OpenMined/mine.js#15]
The mine should be expose a CLI for better bundling in docker and configuration.

Acceptance Criteria:

* `mine help` (or any invalid command) to show start instructions
* `--mineAddress` for passing the blockchain address for the mine to use
* `--sonarAddress` the address of the Sonar smart contract
* `--ipfsUrl` url of the IPFS node
* `--ethereumUrl` url to the ethereum network to use

**Comment by kevinahuber** [comment]
Totally down for that, I can take this!

I intend on using [commanderjs](https://github.com/tj/commander.js/)... any objections?

**Comment by anoff** [comment]
Sounds good! There should already be a `commander` bootstrapped somewhere, just never got around to build it :D
