### ISSUE TITLE
Validate IPFS url format

### ISSUE THREAD

**Issue by anoff** [OpenMined/mine.js#28]
As mentioned in #27 it might be a good idea to validate the `ipfs-url` (maybe also `ethereum-url`?) when the `bin/cli.js` is called. Error behaviour will be more consistent if the wrongly formatted URL is thrown explicitly instead of later on in the process.

Acceptance criteria:
* validate IPFS url for correct [multiaddr](https://github.com/multiformats/multiaddr) format
* tests (if possible 👀)

**Comment by iamtrask** [comment]
@aniket965 has some great ideas for this one

**Comment by vbankov** [comment]
@anoff, @Aniket965 is this issue still open ?

**Comment by anoff** [comment]
@vbankov thanks for bringing this up. Actually as we switched away from `multiaddr` for the IPFS url this is no longer needed.
