### ISSUE TITLE
Calling CLI without arguments should do something useful

### ISSUE THREAD

**Issue by anoff** [OpenMined/mine.js#29]
Currently calling `node bin/cli` without any arguments just exits. It would be nicer to have some sort of feedback of what just happened. Simplest option would be to just render the help text. Open to other solutions though :)

Acceptance Criteria:
* `node bin/cli` tells the user how to start the mine properly

**Comment by Aniket965** [comment]
will do it first

**Comment by anoff** [comment]
I highly encourage to submit individual PRs for issues that can be fixed independently. This one would be closed already 😛
