### ISSUE TITLE
Dockerize mine with IPFS

### ISSUE THREAD

**Issue by anoff** [OpenMined/mine.js#6]
The mine should be dockerized to create an image that includes the mine as well as a running IPFS node.

**Acceptance Critieria**
* automatic build pipeline on dockerhub
* IPFS node is connected to the public network (port routing)
* can access the sonar contract / blockchain net provided by [sonar](https://github.com/OpenMined/Sonar/issues/5)

**Comment by anoff** [comment]
Hmm tried working on this issue but not really sure that putting two huge processes like nodejs and [ipfs](https://github.com/ipfs/go-ipfs/blob/master/Dockerfile) in one docker image. What do you think about bundling monoliths in Docker? @TheOriginalAlex

**Comment by ghost** [comment]
Not a great idea to have multiple processes in a container.  Containers are itself processes and having subprocesses within that process isn't the container way of doing things.  I'd do two containers, one for the mine and another one for ipfs and link them together in a private network through a docker-compose file.

**Comment by anoff** [comment]
Awesome, thanks for your Input. Got the simple Dockerfile down. Now just need to get a docker-compose into it and this thing is done :)
