### ISSUE TITLE
add `docker-compose` to spawn multiple mines

### ISSUE THREAD

**Issue by anoff** [OpenMined/mine.js#7]
> Needs docker knowledge

There should be a `docker-compose` file that allows to spawn a certain amount of mines.
At this state the mines do not expose any ports.

**Acceptance Criteria**:
* all mines are connected to one blockchain node
* each mine is running its own IPFS node
* 10 mines by default
* optional: number of mines can be defined

**Comment by kevinahuber** [comment]
@anoff looking into this, moving the config to `process.env` will allow us to set different configs for each mine in [compose](https://docs.docker.com/compose/compose-file/#environment)

Do you have a preference for env variable? Some devs are oddly opinionated on this, I usually just use [dotenv](https://www.npmjs.com/package/dotenv)

**Comment by anoff** [comment]
hey @kevinahuber I was thinking of building a CLI based interface where you can just pass in all the config stuff. e.g. `mine --contractAddress XYZ --mineAddress ABC --moreStuffToComeLaterOnWhenWeAddFeatures`

Thoughts on that?
I've never used `dotenv` libs tbh... I don't really get why I would define environment variables in a file? You could just define the `ENV` in the compose directly 🤔

**Comment by anoff** [comment]
That'd be my proposal: https://github.com/OpenMined/mine.js/issues/15

**Comment by kevinahuber** [comment]
true- I was thinking when using it outside of compose. But thats kinda not really possible, given how it is all tied together.
